--------------------------------------------------------
--  File created - Thursday-July-30-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_GIAO_DICH
--------------------------------------------------------

   CREATE SEQUENCE  "HUANBANK"."SEQ_GIAO_DICH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_KHACH_HANG
--------------------------------------------------------

   CREATE SEQUENCE  "HUANBANK"."SEQ_KHACH_HANG"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table GIAO_DICH
--------------------------------------------------------

  CREATE TABLE "HUANBANK"."GIAO_DICH" 
   (	"MAGD" NUMBER, 
	"SOTK" VARCHAR2(20 BYTE), 
	"SOTK_DOI" VARCHAR2(20 BYTE), 
	"LOAIGD" VARCHAR2(10 BYTE), 
	"SOTIEN" NUMBER(18,2), 
	"SODUSAUGD" NUMBER(18,2), 
	"THOIGIANGD" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KHACH_HANG
--------------------------------------------------------

  CREATE TABLE "HUANBANK"."KHACH_HANG" 
   (	"MAKH" NUMBER, 
	"HOTEN" VARCHAR2(100 BYTE), 
	"SDT" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"NGAYSINH" DATE, 
	"DIACHI" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAI_KHOAN
--------------------------------------------------------

  CREATE TABLE "HUANBANK"."TAI_KHOAN" 
   (	"SOTK" VARCHAR2(20 BYTE), 
	"MAKH" NUMBER, 
	"MATKHAU" VARCHAR2(256 BYTE), 
	"SODU" NUMBER(18,2) DEFAULT 0, 
	"NGAYTAO" DATE DEFAULT SYSDATE, 
	"TRANGTHAI" VARCHAR2(20 BYTE) DEFAULT 'HOAT_DONG'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HUANBANK.GIAO_DICH
SET DEFINE OFF;
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (1,'doquanghuan1','doquanghuan','CHUYEN',20000,50000,to_timestamp('30-JUL-26 10.39.48.844000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (2,'doquanghuan','doquanghuan1','NHAN',20000,110000,to_timestamp('30-JUL-26 10.39.48.870000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (3,'doquanghuan',null,'NAP',20000,130000,to_timestamp('30-JUL-26 10.48.07.739000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (4,'doquanghuan1','doquanghuan2','CHUYEN',20000,30000,to_timestamp('30-JUL-26 03.16.50.044000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (5,'doquanghuan2','doquanghuan1','NHAN',20000,0,to_timestamp('30-JUL-26 03.16.50.046000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (6,'doquanghuan1',null,'RUT',20000,10000,to_timestamp('30-JUL-26 03.24.13.050000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (7,'doquanghuan1',null,'RUT',20000,-10000,to_timestamp('30-JUL-26 03.24.30.918000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (8,'doquanghuan',null,'RUT',20000,130000,to_timestamp('30-JUL-26 03.30.23.999000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (9,'doquanghuan','doquanghuan1','CHUYEN',50000,80000,to_timestamp('30-JUL-26 03.31.14.274000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (10,'doquanghuan1','doquanghuan','NHAN',50000,60000,to_timestamp('30-JUL-26 03.31.14.275000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into HUANBANK.GIAO_DICH (MAGD,SOTK,SOTK_DOI,LOAIGD,SOTIEN,SODUSAUGD,THOIGIANGD) values (11,'doquanghuan',null,'NAP',20000,100000,to_timestamp('30-JUL-26 03.46.09.141000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into HUANBANK.KHACH_HANG
SET DEFINE OFF;
Insert into HUANBANK.KHACH_HANG (MAKH,HOTEN,SDT,EMAIL,NGAYSINH,DIACHI) values (11,'Huan','0331111999','huannn@gmail.com',to_date('21-DEC-05','DD-MON-RR'),'QT');
Insert into HUANBANK.KHACH_HANG (MAKH,HOTEN,SDT,EMAIL,NGAYSINH,DIACHI) values (14,'huan',null,'ha',to_date('21-DEC-05','DD-MON-RR'),'qr');
Insert into HUANBANK.KHACH_HANG (MAKH,HOTEN,SDT,EMAIL,NGAYSINH,DIACHI) values (15,'huann',null,'oquang@gmail.com',to_date('21-FEB-05','DD-MON-RR'),'do');
Insert into HUANBANK.KHACH_HANG (MAKH,HOTEN,SDT,EMAIL,NGAYSINH,DIACHI) values (9,'Do Quang Huan','0111222554','huan211205@gmail.com',to_date('21-DEC-05','DD-MON-RR'),'Thai Binh');
Insert into HUANBANK.KHACH_HANG (MAKH,HOTEN,SDT,EMAIL,NGAYSINH,DIACHI) values (10,'Do Quang Huan','011122554','huan2112205@gmail.com',to_date('21-DEC-05','DD-MON-RR'),'Thai Binh');
Insert into HUANBANK.KHACH_HANG (MAKH,HOTEN,SDT,EMAIL,NGAYSINH,DIACHI) values (16,'huan','0344238998','huan22220@gmail.com',null,'do');
Insert into HUANBANK.KHACH_HANG (MAKH,HOTEN,SDT,EMAIL,NGAYSINH,DIACHI) values (1,'Do Quang Huan','0355131955','huan2112@gmail.com',null,'Thai Binh');
Insert into HUANBANK.KHACH_HANG (MAKH,HOTEN,SDT,EMAIL,NGAYSINH,DIACHI) values (2,'Do Quang Huan','0111222354','huan21122@gmail.com',null,'Thai Binh');
Insert into HUANBANK.KHACH_HANG (MAKH,HOTEN,SDT,EMAIL,NGAYSINH,DIACHI) values (12,'hihi','0311999299','dhuuann@gmail.com',to_date('21-DEC-05','DD-MON-RR'),'QHHH');
REM INSERTING into HUANBANK.TAI_KHOAN
SET DEFINE OFF;
Insert into HUANBANK.TAI_KHOAN (SOTK,MAKH,MATKHAU,SODU,NGAYTAO,TRANGTHAI) values ('doquanghuan1',11,'2',60000,to_date('29-JUL-26','DD-MON-RR'),'HOAT_DONG');
Insert into HUANBANK.TAI_KHOAN (SOTK,MAKH,MATKHAU,SODU,NGAYTAO,TRANGTHAI) values ('doquanghuan2',14,'doquanghuan',20000,to_date('30-JUL-26','DD-MON-RR'),'HOAT_DONG');
Insert into HUANBANK.TAI_KHOAN (SOTK,MAKH,MATKHAU,SODU,NGAYTAO,TRANGTHAI) values ('doquanghuan3',15,'doquanghuan',0,to_date('30-JUL-26','DD-MON-RR'),'HOAT_DONG');
Insert into HUANBANK.TAI_KHOAN (SOTK,MAKH,MATKHAU,SODU,NGAYTAO,TRANGTHAI) values ('doquanghuan',9,'huan123',100000,to_date('29-JUL-26','DD-MON-RR'),'HOAT_DONG');
Insert into HUANBANK.TAI_KHOAN (SOTK,MAKH,MATKHAU,SODU,NGAYTAO,TRANGTHAI) values ('hahaaa',10,'huan123',20000,to_date('29-JUL-26','DD-MON-RR'),'HOAT_DONG');
Insert into HUANBANK.TAI_KHOAN (SOTK,MAKH,MATKHAU,SODU,NGAYTAO,TRANGTHAI) values ('doquanghuan4',16,'doquanghuan',0,to_date('30-JUL-26','DD-MON-RR'),'HOAT_DONG');
Insert into HUANBANK.TAI_KHOAN (SOTK,MAKH,MATKHAU,SODU,NGAYTAO,TRANGTHAI) values ('doqunhun',12,'112',0,to_date('29-JUL-26','DD-MON-RR'),'HOAT_DONG');
--------------------------------------------------------
--  DDL for Index UQ_KHACHHANG_SDT
--------------------------------------------------------

  CREATE UNIQUE INDEX "HUANBANK"."UQ_KHACHHANG_SDT" ON "HUANBANK"."KHACH_HANG" ("SDT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_GIAODICH_SOTK_DOI
--------------------------------------------------------

  CREATE INDEX "HUANBANK"."IDX_GIAODICH_SOTK_DOI" ON "HUANBANK"."GIAO_DICH" ("SOTK_DOI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_KHACHHANG_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "HUANBANK"."UQ_KHACHHANG_EMAIL" ON "HUANBANK"."KHACH_HANG" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_GIAODICH_SOTK
--------------------------------------------------------

  CREATE INDEX "HUANBANK"."IDX_GIAODICH_SOTK" ON "HUANBANK"."GIAO_DICH" ("SOTK", "THOIGIANGD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_GIAODICH_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HUANBANK"."TRG_GIAODICH_ID" 
BEFORE INSERT ON GIAO_DICH
FOR EACH ROW
 WHEN (NEW.MaGD IS NULL) BEGIN
    :NEW.MaGD := seq_giao_dich.NEXTVAL;
END;

/
ALTER TRIGGER "HUANBANK"."TRG_GIAODICH_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_KHACHHANG_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HUANBANK"."TRG_KHACHHANG_ID" 
BEFORE INSERT ON KHACH_HANG
FOR EACH ROW
 WHEN (NEW.MaKH IS NULL) BEGIN
    :NEW.MaKH := seq_khach_hang.NEXTVAL;
END;

/
ALTER TRIGGER "HUANBANK"."TRG_KHACHHANG_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table KHACH_HANG
--------------------------------------------------------

  ALTER TABLE "HUANBANK"."KHACH_HANG" MODIFY ("HOTEN" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."KHACH_HANG" ADD PRIMARY KEY ("MAKH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUANBANK"."KHACH_HANG" ADD CONSTRAINT "UQ_KHACHHANG_SDT" UNIQUE ("SDT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUANBANK"."KHACH_HANG" ADD CONSTRAINT "UQ_KHACHHANG_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GIAO_DICH
--------------------------------------------------------

  ALTER TABLE "HUANBANK"."GIAO_DICH" MODIFY ("SOTK" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."GIAO_DICH" MODIFY ("LOAIGD" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."GIAO_DICH" MODIFY ("SOTIEN" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."GIAO_DICH" MODIFY ("SODUSAUGD" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."GIAO_DICH" MODIFY ("THOIGIANGD" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."GIAO_DICH" ADD CONSTRAINT "CK_GIAODICH_LOAI" CHECK (LoaiGD IN ('NAP', 'RUT', 'CHUYEN', 'NHAN')) ENABLE;
  ALTER TABLE "HUANBANK"."GIAO_DICH" ADD CONSTRAINT "CK_GIAODICH_SOTIEN" CHECK (SoTien > 0) ENABLE;
  ALTER TABLE "HUANBANK"."GIAO_DICH" ADD PRIMARY KEY ("MAGD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAI_KHOAN
--------------------------------------------------------

  ALTER TABLE "HUANBANK"."TAI_KHOAN" MODIFY ("MAKH" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."TAI_KHOAN" MODIFY ("MATKHAU" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."TAI_KHOAN" MODIFY ("SODU" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."TAI_KHOAN" MODIFY ("NGAYTAO" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."TAI_KHOAN" MODIFY ("TRANGTHAI" NOT NULL ENABLE);
  ALTER TABLE "HUANBANK"."TAI_KHOAN" ADD CONSTRAINT "CK_TAIKHOAN_SODU" CHECK (SoDu >= 0) ENABLE;
  ALTER TABLE "HUANBANK"."TAI_KHOAN" ADD CONSTRAINT "CK_TAIKHOAN_TRANGTHAI" CHECK (TrangThai IN ('HOAT_DONG', 'KHOA', 'DONG')) ENABLE;
  ALTER TABLE "HUANBANK"."TAI_KHOAN" ADD PRIMARY KEY ("SOTK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GIAO_DICH
--------------------------------------------------------

  ALTER TABLE "HUANBANK"."GIAO_DICH" ADD CONSTRAINT "FK_GIAODICH_TAIKHOAN" FOREIGN KEY ("SOTK")
	  REFERENCES "HUANBANK"."TAI_KHOAN" ("SOTK") ENABLE;
  ALTER TABLE "HUANBANK"."GIAO_DICH" ADD CONSTRAINT "FK_GIAODICH_TAIKHOAN_DOI" FOREIGN KEY ("SOTK_DOI")
	  REFERENCES "HUANBANK"."TAI_KHOAN" ("SOTK") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAI_KHOAN
--------------------------------------------------------

  ALTER TABLE "HUANBANK"."TAI_KHOAN" ADD CONSTRAINT "FK_TAIKHOAN_KHACHHANG" FOREIGN KEY ("MAKH")
	  REFERENCES "HUANBANK"."KHACH_HANG" ("MAKH") ENABLE;
